select *from EMPLOYEES;
select * from departments;
select FIRST_NAME,LAST_NAME,DEPARTMENT_NAME
from EMPLOYEES e left join DEPARTMENTS d
on e.DEPARTMENT_ID = d.DEPARTMENT_ID;
select CUSTOMER_ID,FIRST_NAME,LAST_NAME,CUSTOMER.ADDRESS_ID,ADDRESS,PHONE from CUSTOMER left outer join  address
on CUSTOMER.ADDRESS_ID=ADDRESS.address_ID
where CUSTOMER.address_id is null;
select *from CUSTOMER full outer join ADDRESS on CUSTOMER.ADDRESS_ID=ADDRESS.ADDRESS_ID
where CUSTOMER.ADDRESS_ID is null or ADDRESS.ADDRESS_ID is null;


select CUSTOMER_ID,FIRST_NAME,LAST_NAME,CUSTOMER.ADDRESS_ID,ADDRESS.ADDRESS_ID ADDRESS,PHONE
from CUSTOMER left outer join ADDRESS
                              on CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID
where CUSTOMER.ADDRESS_ID IS NULL;
